name: lint, build, test and deploy

on:
  push:
    branches: ["partie-3/chapitre-2"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16, 18]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install nodes ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run:
          npm run lint

      - name: Save artifacts (create archive)
        run: tar -czf node_modules.tar.gz node_modules
        # The above command creates a compressed archive (node_modules.tar.gz) of the node_modules directory

        # Save the archive as an artifact
      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: node-modules
          path: node_modules.tar.gz

  build-and-test:
    runs-on: ubuntu-latest
    needs: lint

    strategy:
      matrix:
        node: [16, 18]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install nodes ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: node-modules
          path: .

      - name: Extract node_modules
        run: tar -xzf node_modules.tar.gz
        # The above command extracts the contents of node_modules.tar.gz

      - name: test
        run: npm run test

      - name: typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-test

    strategy:
      matrix:
        node: [16, 18]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install nodes ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Download node_modules
        uses: actions/download-artifact@v2
        with:
          name: node-modules
          path: .

      - name: Extract node_modules
        run: tar -xzf node_modules.tar.gz
        # The above command extracts the contents of node_modules.tar.gz

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v3

        # Set dist branch as output
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload dist repository
          path: "./src/dist/"
          # Upload to dist branch
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
