name: A failling Workflow

on:
  push:
    branches: ["partie-2/chapitre-2/section-2"]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Build the app
        run: npm run build

      - name: Test the app
        run: npm run test